version: '3'

services:
  postgresql:
    restart: always
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - ./pgdata:./pgdata
    environment:
      - POSTGRES_USER=collaboux
      - POSTGRES_PASSWORD=collaboux
      - PGDATA=/pgdata
      - POSTGRES_DB=collaboux
    networks:
      collaboux_network:
        ipv4_address: 172.18.1.1

  redis:
    image: redis
    entrypoint: redis-server --appendonly yes
    restart: always
    ports:
      - 6379:6379
    networks:
      collaboux_network:
        ipv4_address: 172.18.1.2

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
    networks:
      collaboux_network:
        ipv4_address: 172.18.1.3

  kafka:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    depends_on:
      - "zookeeper"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "USER_LOGIN:1:1"
    networks:
      collaboux_network:
        ipv4_address: 172.18.1.4

networks:
  collaboux_network:
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16