version: '3'

services:
  kafka-app:
    restart: always
    build:
      context: docker-compose.yml
      args:
        PORT: 8081
    ports:
      - 8081:8081
    depends_on:
      - redis
      - kafka
      - zookeeper
      - postgresql
    networks:
      - kafka-service_default